### PR TITLE
Port of CLI to NET 6 for native support

### PR DESCRIPTION
**Pull request by AlmightyLks**
As already attempted with PR https://github.com/0x78654C/PwM/pull/8 , I went into the effort of successfully porting the cli application to .NET 6, so that there is no unnecessary need for wine / mono with it's messy workarounds, just for a small cli app.
FIY, I made sure to adjust my changes so that all the tests pass. :)

Changes include:  
- PwMLib .NET Framework 4.7.2 -> .NET Standard 2.0
- PwM_CLI .NET Framework 4.7.2 -> .NET 6
- PwM Mkb.ClipBoardManager NuGet -> TextCopy NuGet (400 downloads bootleg vs 4+ Million)
- Unit.Tests added Xunit.StaFact NuGet, in order to let one of the unit tests pass
  - Your classes are primarily within your GUI application, which really wants to have the calling thread to be marked as STA, else it throws an exception once you try to access anything from any type (`GlobalVariables.accountPassword` in this case)

Those are the primary changes. I'd ask you to check whether these changes affect functionality on your system, which are not included in your test suit

Also, some remarks:  
1\)  
The general convention with project names within a solution is `ProjectName.SubCategory`  
Which would look something like:  
`PwM` -> `PwM.GUI`  
`PwM_CLI` -> `PwM.CLI`  
`PwMLib` -> `PwM.Core`  
`Unit.Tests` -> `PwM.Tests`  
  
2\)  
You should really try to separate GUI and business logic  
Having static global variables caused quite a few issues  
Your static global variables just having 1 GUI-specific field (ListView) meant that I couldn't move it out of the GUI project to solve the STA issue

### CODE REVIEW

**Comment by AlmightyLks** [comment]
Also, checkout the build output path, i wasn't quite sure how it was configured

**Comment by 0x78654C** [comment]
Hello. Can you change the target  branch from main to v1.1.3 please? I will look over your changes. We tried till now a similar aproach but seems we have errors on decryption . Will check. Thank you!

**Comment by AlmightyLks** [comment]
By the way, I just did a test publish.
If you're worried about needing to install runtimes, the self-contained publish of the CLI has a trivial size 
linux-x64: ~13.8MB
win-x86: ~15.8MB

Just in case you're worried about the user having to install a runtime for NET 6, as opposed to .NET Fx which is pre-installed with windows

**Comment by 0x78654C** [comment]
Ok. Btw can you keep the Mkb.ClipBoardManager please. Is Michael lib. He did a nice job 😁

**Comment by AlmightyLks** [comment]
I see, but why reinvent the wheel 🤔

Edit:
Looked at it, it is a convenient wrapper around the STA threading issue 😄

**Comment by AlmightyLks** [comment]
Will do once I'm on my pc in a bit

**Comment by 0x78654C** [comment]
Thank you 😁

**Comment by 0x78654C** [comment]
LGTM, will port WPF too for fix decryption issues

**Pull request merged**
